Re-add ApiProperty.dataType which was accidentally removed with 3f95978b
As of 3f95978b, compilation fails with the message:
  SwaggerJsonSchemaProvider.scala:205: error: value dataType is not a
  member of com.wordnik.swagger.annotations.ApiProperty

This commit re-adds the dataType field and now it builds and all tests
pass.